title: My awesome trip across Europe
author: GitHub nobody
theme: minima
email: nobody@example.com
description: I share my travel experience across Europe with plenty of tips to help you do the same and avoid traps.
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  thewebshaper # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
